In [1]:
from utils import *

import pandas as pd

In [2]:
sql = r"""
SELECT 
    eve_id,
    eve_title,
    eve_vacancy,
    eve_workload,
    eve_start_date,
    eve_end_date,
    eve_start_hour,
    eve_end_hour,
    eve_enrollment_start,
    eve_enrollment_end,
    eve_speaker_name,
    eve_audience,
    eve_requirements,
    eve_creation_date,
    fre_enr_stu_id,
    fre_cla_id,
    fre_status,
    stu_session,
    stu_name,
    stu_cpf,
    stu_phone,
    stu_gender,
    stu_birth_date,
    stu_creation_date,
    stu_last_login,
    stu_email
FROM
    event,
    frequency,
    student
WHERE
    eve_id = fre_enr_eve_id
        AND stu_id = fre_enr_stu_id
        AND eve_start_date BETWEEN '2021.04.23' AND '2021.12.31'
    """

db_con = OceanDB()
df = pd.read_sql(sql, db_con.mydb)
df.to_csv('ocean_online_events_second_year.csv', index=False)  
df

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,fre_status,stu_session,stu_name,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,Ausente,1,Orleans Claus dos Santos,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,Ausente,1,Rafael Margiotto De Aguiar,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaT,aguiar.rafaelm@gmail.com
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,Ausente,1,ANGELO LOPES,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaT,anglops@gmail.com
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,Ausente,1,Gerson Souza Da Cunha,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaT,gerson.cunha@outlook.com
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,Ausente,1,Gabriel de Queiroz Sousa,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88797,2795,Ocean Launch - T5 - Métricas do Produto - T2,15,02:00,2021-12-15,2021-12-15,19:00,21:00,1970-01-01,1970-01-01,...,Ausente,0,Matheus Colhyêr,01855338254,(92) 98456-6646,M,1995-03-21,2021-06-29 17:01:20,2021-06-29 17:02:02,m.jacob@sidi.org.br
88798,2795,Ocean Launch - T5 - Métricas do Produto - T2,15,02:00,2021-12-15,2021-12-15,19:00,21:00,1970-01-01,1970-01-01,...,Presente,0,Orange Marques Dos Santos,58541063291,92996047908,M,1974-08-13,2022-01-10 19:10:52,2021-09-08 16:51:11,orangemarques@gmail.com
88799,2795,Ocean Launch - T5 - Métricas do Produto - T2,15,02:00,2021-12-15,2021-12-15,19:00,21:00,1970-01-01,1970-01-01,...,Presente,0,Elaine Pires De Freitas,75242486287,92993112025,F,1984-02-22,2022-01-10 19:10:52,2021-09-08 23:33:03,ela.piresquimica@gmail.com
88800,2795,Ocean Launch - T5 - Métricas do Produto - T2,15,02:00,2021-12-15,2021-12-15,19:00,21:00,1970-01-01,1970-01-01,...,Presente,0,Thalle Andre Alves,01551117282,92981956798,M,1991-10-27,2022-01-10 19:10:52,2021-09-27 18:26:24,thalleandre2710@gmail.com
88801,2795,Ocean Launch - T5 - Métricas do Produto - T2,15,02:00,2021-12-15,2021-12-15,19:00,21:00,1970-01-01,1970-01-01,...,Ausente,0,Alexandre Bastos,00972884203,92988095003,M,1991-07-24,2022-01-10 19:10:11,2021-09-27 18:42:57,alexandre3k39@gmail.com

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_start_hour,eve_end_hour,eve_enrollment_open,eve_enrollment_start,eve_enrollment_end,eve_speaker_name,eve_status,eve_evet_id,eve_event_id,eve_trilha
0,1828,Palestra: Introdução ao Desenvolvimento de Jog...,500,02:00,2020-04-23,15:00,17:00,0.0,2020-04-13,2020-04-23,Prof. Sylker Teles,Inativo,22,NaN,GME
1,1830,M1 - Inteligência artificial: entenda o que é ...,500,02:00,2020-04-23,11:00,13:00,0.0,2020-04-13,2020-04-23,Prof. Mario Augusto Bessa de Figueiredo,Publicado,22,NaN,IAR
2,1831,Palestra: Assistente Virtual de Voz em Bixby -...,500,02:00,2020-04-28,11:00,13:00,0.0,2020-04-13,2020-04-28,Prof. DSc. Tiago de Melo,Publicado,22,NaN,BXB
3,1832,I1 - Introdução a Internet das Coisas (IoT),500,01:00,2020-04-29,18:00,19:00,0.0,2020-04-13,2020-04-29,Prof. DSc. Maurício Figueiredo,Publicado,22,NaN,IOT
4,1833,M2 - Inteligência Artificial - Fundamentos da ...,500,01:00,2020-04-30,16:00,17:00,0.0,2020-04-13,2020-04-30,Prof. DSc. João Batista Ponciano,Publicado,22,NaN,IAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,2295,Assistente Virtual de Voz em Bixby - Trazendo ...,500,02:00,2021-04-19,16:00,18:00,0.0,2021-03-19,2021-04-19,Prof. DSc. Tiago de Melo,Publicado,28,NaN,BXB
457,2300,Introdução ao Frontend Web com React,500,03:00,2021-04-20,14:00,17:00,0.0,2021-04-09,2021-04-20,Prof. Antonio de Carvalho,Publicado,22,NaN,FRTEND
458,2301,Laboratório de Frontend Web com React,500,03:00,2021-04-20,18:00,21:00,0.0,2021-04-09,2021-04-20,Prof. Antonio de Carvalho,Publicado,22,NaN,FRTEND
459,2308,Ocean Beginner (Parte 3),180,02:30,2021-04-13,19:00,21:30,1.0,1970-01-01,1970-01-01,Mentores Ocean,Publicado,32,NaN,OUTROS
460,2309,Ocean Beginner (Parte 4),180,02:30,2021-04-14,19:00,21:30,NaN,1970-01-01,1970-01-01,Mentores Ocean,Publicado,23,NaN,OUTROS